In [35]:
import numpy as np
import pandas as pd
data = pd.read_csv('/content/heart.csv')
data.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [36]:
x = data.drop(['output'],axis=1)
y = data['output']
x.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  
0    0      1  
1    0      2  
2    0      2  
3    0      2  
4    0      2

In [21]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: output, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [38]:
x_train.shape

(242, 13)

In [39]:
x_test.shape

(61, 13)

KNN

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [40]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [41]:
predictions = knn.predict(x_test)
predictions

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,predictions)
ac = accuracy_score(y_test,predictions)

In [43]:
print(cm)

[[17 14]
 [ 5 25]]


In [44]:
print(ac)

0.6885245901639344


#PCA

In [68]:
from sklearn.decomposition import PCA # PCA is only reduce the dimentionality means columns
pca = PCA(n_components=9)
x_reduce_train = pd.DataFrame(pca.fit_transform(x_train))
x_reduce_test = pd.DataFrame(pca.fit_transform(x_test))

In [69]:
x_reduce_train.shape

(242, 9)

In [70]:
x_reduce_test.shape

(61, 9)

To test PCA use KNN algorithum again

In [71]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [72]:
knn.fit(x_reduce_train,y_train)

KNeighborsClassifier()

In [73]:
reduce_predictions = knn.predict(x_reduce_test)
reduce_predictions

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,reduce_predictions)
ac = accuracy_score(y_test,reduce_predictions)

In [75]:
print(cm)

[[16 15]
 [ 8 22]]


In [76]:
print(ac)

0.6229508196721312
